### PR TITLE
Filter unwanted product / variant attributes on creation

### LINKED ISSUE #775: Variant#serializable_hash in 9.2.0
Hi folks,

Outside of a `ShopifyApp` session block, I was trying to call `Variant#as_json`, and kept getting the very unhelpful error:
`TypeError (compared with non class/module)` with no traceback.

I was able to track it down to this recent addition by @marschattha in `lib/shopify_api/resources/variant.rb`:

```ruby
def allow_inventory_params?
  Base.api_version < ApiVersion.find_version('2019-10')
end
```

If you're using `ShopifyApp` and do something like:
```ruby
product = shop.with_shopify_session { ShopifyAPI::Product.find(XXX) } 
```

the `Base.api_version` the api version is only set within the block, and is otherwise `ShopifyAPI::ApiVersion::NullVersion` causing the `TypeError` on comparison.

It feels weird to not be able to serialize an object outside of a session block.  Not sure how/if you'd like to solve this issue, but thought I might share my research here in case others experience the same problem.

### PR DESCRIPTION
**Pull request by paulomarg**
Fixes #775 

## Why am I making these changes?

We had reports that the changes made in #731 were causing the JSON serialization of API objects to break when `Base.api_version` wasn't set, for instance outside the scope of a temp session.

The issue here was that we were filtering the fields out only when serializing the Product / Variant objects, rather than removing them altogether (even though they were no longer allowed in the API after version `2019-10`).

## What is this PR doing?

This PR changes those objects so that we remove the fields when the object is first created, so that we don't need to check later on.

### CODE REVIEW

File: lib/shopify_api/resources/product.rb [hunk 1]
```diff
@@ -5,6 +5,11 @@ class Product < Base
 
     early_july_pagination_release!
 
+    def initialize(*args, **kwargs)
+      super(*args, **kwargs)
```
Comment (andyw8) [inline lib/shopify_api/resources/product.rb:9]: This should be fine as just `super`.

**Comment by andyw8** [comment]
Since 2019-10 is no longer supported, would we be able to remove that check?

**Comment by paulomarg** [comment]
> Since 2019-10 is no longer supported, would we be able to remove that check?

Seems we may not be able to fully drop this code yet, as the Admin API still returns these fields and explicitly forbids saving them. So if we remove this code to filter out these fields, we'll end up trying to save them and that may lead to API requests failing.

**Review by tanema — APPROVED** [review]

**Review by tanema — APPROVED** [review]
